name: Dependency Scan

"on":
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@a9eee5154fef6d6c9b6483bdd95b38862117874d
    permissions:
      contents: read
      id-token: write
