name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: true

      - uses: wevm/changelogs@a160c1637ff9cf1529cddedd17cca47a276423e8 # changelogs@0.6.3
        with:
          ecosystem: python
          python-version: '3.12'
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          conventional-commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
